# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'
  Build.Repository.Name: 'yuvraj3010/python-hello-world'

steps:
- task: Docker@2
  displayName: Login to Docker Hub
  inputs: 
    command: login
    containerRegistry: 'https://hub.docker.com/'
- task: Docker@2
  displayName: Build
  inputs:
    command: build
    #containerRegistry: 'https://hub.docker.com/'
    repository: $(imageName)
- task: Docker@2
  displayName: Push
  inputs:
    command: Push
    containerRegistry: 'https://hub.docker.com/'
    repository: $(Build.Repository.Name)
    tags: |
      tag1
      tag2
